server:
  port: 8764


spring:
  application:
    name: WYK

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false


eureka:
  client:
    service-url:
      defaultZone:  http://10.10.10.254:8761/eureka/
